# Generated by Django 4.1.7 on 2023-03-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
