# Generated by Django 5.2.7 on 2025-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('SUPER', 'Super Category'), ('SUB', 'Sub Category'), ('REGULAR', 'Regular Category')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='top_level_category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
