# Generated by Django 5.2.7 on 2025-10-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0002_alter_blogpost_options_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_updated', '-date_created'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
