# Generated by Django 4.1.7 on 2023-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0003_alter_blog_date_created_alter_blog_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imag',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
