# Generated by Django 4.1.7 on 2023-03-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0003_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateField(),
        ),
    ]
