# Generated by Django 4.1.7 on 2023-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0004_blog_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imag',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images/'),
        ),
    ]
