# Generated by Django 5.2.7 on 2025-10-19 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0004_category_alter_comment_options_comment_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 19, 1, 54, 0, 173961, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
