# Generated by Django 4.1.7 on 2023-03-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0004_alter_blogpost_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
