# Generated by Django 4.1.7 on 2023-03-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0006_alter_blog_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='imag',
            new_name='add_image',
        ),
    ]
