# Generated by Django 5.2.7 on 2025-10-24 16:48

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0007_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
