# Generated by Django 5.2.7 on 2025-10-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0010_alter_blogpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=models.TextField(),
        ),
    ]
