# Generated by Django 5.2.7 on 2025-10-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0011_alter_blogpost_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='LEGGETECH', max_length=50, unique=True),
        ),
    ]
