# Generated by Django 5.2.7 on 2025-10-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0012_alter_customuser_options_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times product has been viewed'),
        ),
    ]
