# Generated by Django 5.2.7 on 2025-11-04 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0015_authorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorapplication',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user account if the applicant is already registered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='author_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
