# Generated by Django 5.2.7 on 2025-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0018_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Your Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Your Twitter profile URL'),
        ),
    ]
