# Generated by Django 5.2.7 on 2025-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstblog', '0019_authorprofile_facebook_url_authorprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
    ]
